runtime: go
api_version: go1.9
service: pdf-api
threadsafe: true
automatic_scaling:
    max_concurrent_requests: 80
    min_pending_latency: 100ms
    max_pending_latency: 200ms
    target_throughput_utilization: 0.95

handlers:
- url: /.*
  secure: always
  script: _go_app